# quiz_scaffold.py
from weasyprint import HTML
from datetime import datetime
import os

def generate_quiz_pdf(questions):
  quiz_html = """
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Class Quiz</title>
  <style>
    @page {
      size: A4;
      margin: 2cm;
      @top-center {
        content: "Page " counter(page) " | intended for educational use ONLY";
        font-size: 10px;
        color: #555;
      }
      @bottom-center {
        content: "Generated by Image Training Summary & Quiz Generator WebApp";
        font-size: 9px;
        color: #777;
      }
    }
    body {
      font-family: "Helvetica", sans-serif;
      color: #222;
      line-height: 1.7;
    }
    h1 {
      text-align: center;
      color: #2c3e50;
      margin-bottom: 1em;
      font-size: 22px;
      text-transform: uppercase;
    }
    .student-info {
      margin: 25px 0 40px 0;
      padding: 12px;
      border: 1px solid #ccc;
      border-radius: 8px;
      font-size: 13px;
    }
    .field-label {
      display: inline-block;
      width: 15%;
      font-weight: bold;
    }
    .input-boxes {
      display: inline-block;
      margin-right: 20px;
    }
    .box {
      display: inline-block;
      width: 18px;
      height: 22px;
      border: 1px solid #333;
      margin: 0 1px;
    }
    .question {
      margin: 25px 0;
      padding: 15px;
      border: 1px solid #eee;
      border-radius: 6px;
    }
    .question strong {
      display: block;
      margin-bottom: 10px;
    }
    .answer-choice {
      margin: 8px 0 8px 25px;
      font-size: 13px;
    }
    .checkbox {
      display: inline-block;
      width: 14px;
      height: 14px;
      border: 1px solid #333;
      margin-right: 8px;
    }
  </style>
</head>
<body>
  <h1>Class Quiz</h1>
  
  <div class="student-info">
    <div>
      <span class="field-label">Name:</span>
      <span class="input-boxes">""" + "".join('<span class="box"></span>' for _ in range(20)) + """</span>
    </div>
    <div>
      <span class="field-label">Roll No.:</span>
      <span class="input-boxes">""" + "".join('<span class="box"></span>' for _ in range(6)) + """</span>
    </div>
    <div>
      <span class="field-label">Grade:</span>
      <span class="input-boxes">""" + "".join('<span class="box"></span>' for _ in range(4)) + """</span>
    </div>
    <div>
      <span class="field-label">Date:</span>
      <span class="input-boxes">""" + "".join('<span class="box"></span>' for _ in range(10)) + """</span>
    </div>
  </div>
  
  <!-- Example Question Block -->

"""


  answer_html = """
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Answer Book</title>
  <style>
    @page {
      size: A4;
      margin: 2cm;
      @top-center {
        content: "Page " counter(page) " | Intended for Educational Use ONLY";
        font-size: 10px;
        color: #555;
      }
      @bottom-center {
        content: "Generated by Image Training Summary & Quiz Generator WebApp";
        font-size: 9px;
        color: #777;
      }
    }
    body {
      font-family: "Helvetica", sans-serif;
      color: #222;
      line-height: 1.7;
    }
    h1 {
      text-align: center;
      color: #8e44ad;
      margin-bottom: 1em;
      font-size: 22px;
      text-transform: uppercase;
    }
    .question {
      margin: 25px 0;
      padding: 15px;
      border: 1px solid #eee;
      border-radius: 6px;
    }
    .question strong {
      display: block;
      margin-bottom: 10px;
    }
    .answer-choice {
      margin: 8px 0 8px 25px;
      font-size: 13px;
    }
    .correct {
      font-weight: bold;
      color: #27ae60;
    }
  </style>
</head>
<body>
  <h1>Answer Book</h1>
  
  <!-- Example Question Block -->
"""

  for question in questions:
    quiz_html += f"""

      <div class="question">
        <strong>Q. {question['question']}</strong>

    """

    answer_html += f"""

      <div class="question">
        <strong>Q. {question['question']}</strong>
    """

    for answer_choice in question['answer_choices']:
      quiz_html += f"""
        <div class="answer-choice"><span class="checkbox"></span> {answer_choice}</div>
      """

      if answer_choice == question['answer']:
        answer_html += f"""
        <div class="answer-choice correct">  {answer_choice}✅</div>
        """
      else:
        answer_html += f"""
        <div class="answer-choice">  {answer_choice}</div>
        """


    answer_html += f"""
      </div>
    """
    
    quiz_html += f"""

      </div>
    """
  
  quiz_html += """

</body>
</html>
"""
  answer_html += """

</body>
</html>
"""

  if not os.path.isdir("pdfs"):
    os.makedirs("pdfs")

  
  date_time = datetime.now()

  HTML(string=quiz_html).write_pdf(f"pdfs/quiz_worksheet-{date_time}.pdf")
  HTML(string=answer_html).write_pdf(f"pdfs/answer_book-{date_time}.pdf")